# Generated by Django 4.2.5 on 2023-12-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property_decorator", "0002_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=50)),
            ],
        ),
    ]
