# Generated by Django 4.2.6 on 2023-12-04 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("model_inheritance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cname", models.CharField(max_length=70)),
                ("city", models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name="MyStudent",
            fields=[
                (
                    "examcenter_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="model_inheritance.examcenter",
                    ),
                ),
                ("name", models.CharField(max_length=70)),
                ("roll", models.IntegerField()),
            ],
            bases=("model_inheritance.examcenter",),
        ),
    ]
