# Generated by Django 4.2.6 on 2023-12-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_inheritance", "0002_examcenter_mystudent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Center",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cname", models.CharField(max_length=70)),
                ("city", models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name="MyCenter",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("model_inheritance.center",),
        ),
    ]
