# Generated by Django 4.1.4 on 2023-04-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_template_tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees',
            field=models.IntegerField(default=0),
        ),
    ]
